@startuml class
participant "Combianet" as A
participant "Calculate" as B
participant "Factorial" as C
A-> B:add(int x) x>=1
B-->C:xn!(void)

loop factorial
A->B:n!(x)
alt if x<=1
A-->B: print(x)
B-->C: print
end alt
end loop
note over B,C
Factorial
end note

@enduml