@startuml
skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}

Factorial <-- "Combination"
activate Factorial
"Combination" -> "Calculate":  (  10)
activate Combination
deactivate "Calculate"
User -->  "Calculate":   add(5)
activate "Calculate"
"Calculate" -> "User": display (120)
deactivate "Calculate"
User -->  "Calculate": add(3)
activate "Calculate"
"Calculate" -> "User": display (6)
deactivate "Calculate"
User -->  "Calculate": add(2)
activate "Calculate"
"Calculate" -> "User": display (2)
deactivate "Calculate"
"Calculate" --> "Combination": (  5.2)
deactivate "Combination"
deactivate "Combination"
Factorial -> "Calculate"
deactivate Factorial
actor User




@enduml
